import { Dimensions, StyleSheet } from 'react-native';
import { COLORS } from '../../utils/theme';

const { width, height } = Dimensions.get('window');

export default StyleSheet.create({
  container: { flex: 1, backgroundColor: '#f8f9fa' },
  loaderContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#f8f9fa',
    gap: 12,
  },
  loaderText: {
    fontFamily: 'Poppins-Regular',
    fontSize: 14,
    color: '#666',
  },
  notFoundContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#f8f9fa',
    gap: 16,
  },
  notFound: {
    fontFamily: 'Poppins-Medium',
    fontSize: 16,
    color: COLORS.textLight,
  },
  backBtn: {
    paddingHorizontal: 24,
    paddingVertical: 12,
    backgroundColor: COLORS.primary,
    borderRadius: 25,
  },
  backBtnText: {
    color: '#fff',
    fontFamily: 'Poppins-SemiBold',
  },
  gallery: {
    position: 'relative',
    backgroundColor: '#000',
  },
  statusBarGradient: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    zIndex: 2,
  },
  mainImage: {
    width,
    height: height * 0.45,
  },
  imagePlaceholder: {
    backgroundColor: '#f0f0f0',
    justifyContent: 'center',
    alignItems: 'center',
  },
  dotsContainer: {
    position: 'absolute',
    bottom: 14,
    left: 0,
    right: 0,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 6,
  },
  dot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: 'rgba(255,255,255,0.5)',
  },
  dotActive: {
    width: 18,
    height: 6,
    borderRadius: 3,
    backgroundColor: '#fff',
  },
  imageCounter: {
    position: 'absolute',
    bottom: 14,
    right: 16,
    backgroundColor: 'rgba(0,0,0,0.45)',
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 10,
  },
  imageCounterText: {
    color: '#fff',
    fontSize: 11,
    fontFamily: 'Poppins-Medium',
  },
  favoriteBtn: {
    position: 'absolute',
    top: 16,
    right: 16,
    backgroundColor: 'rgba(0,0,0,0.4)',
    borderRadius: 25,
    padding: 10,
    zIndex: 1,
  },
  backBtnGallery: {
    position: 'absolute',
    top: 16,
    left: 16,
    backgroundColor: 'rgba(0,0,0,0.4)',
    borderRadius: 25,
    padding: 10,
    zIndex: 1,
  },
  shareBtn: {
    position: 'absolute',
    top: 16,
    right: 70,
    backgroundColor: 'rgba(0,0,0,0.4)',
    borderRadius: 25,
    padding: 10,
    zIndex: 1,
  },
  content: {
    padding: 20,
  },
  titleRow: {
    flexDirection: 'row',
    marginBottom: 12,
  },
  badges: {
    flexDirection: 'row',
    gap: 10,
  },
  transactionChip: {
    backgroundColor: COLORS.primary,
  },
  statusChip: {
    backgroundColor: COLORS.secondary,
  },
  availableChip: {
    backgroundColor: '#10b981',
  },
  unavailableChip: {
    backgroundColor: '#ef4444',
  },
  title: {
    fontFamily: 'Poppins-Bold',
    fontSize: 24,
    color: '#333',
    marginBottom: 8,
  },
  locationRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginBottom: 12,
  },
  location: {
    fontFamily: 'Poppins-Regular',
    fontSize: 14,
    color: '#666',
    flex: 1,
  },
  price: {
    fontSize: 28,
    fontFamily: 'Poppins-Bold',
    color: COLORS.primary,
    marginBottom: 8,
  },
  perMonth: {
    fontSize: 14,
    fontFamily: 'Poppins-Regular',
    color: '#666',
  },
  ratingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginTop: 4,
  },
  ratingText: {
    fontFamily: 'Poppins-Medium',
    fontSize: 13,
    color: '#666',
  },
  divider: {
    marginVertical: 20,
    backgroundColor: '#e9ecef',
  },
  ownerSection: {
    marginBottom: 8,
  },
  sectionTitle: {
    fontFamily: 'Poppins-SemiBold',
    fontSize: 18,
    color: '#333',
    marginBottom: 12,
  },
  ownerCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 16,
    padding: 16,
    backgroundColor: '#fff',
    borderRadius: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 2,
  },
  ownerInfo: {
    flex: 1,
  },
  ownerAvatar: {
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: '#e9ecef',
  },
  ownerAvatarPlaceholder: {
    width: 60,
    height: 60,
    borderRadius: 30,
    justifyContent: 'center',
    alignItems: 'center',
  },
  ownerNameRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 2,
  },
  ownerName: {
    fontFamily: 'Poppins-SemiBold',
    fontSize: 16,
    color: '#333',
  },
  verifiedBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 3,
    backgroundColor: '#10b981',
    borderRadius: 10,
    paddingHorizontal: 6,
    paddingVertical: 2,
  },
  verifiedText: {
    fontFamily: 'Poppins-Medium',
    fontSize: 10,
    color: '#fff',
  },
  ownerContact: {
    fontFamily: 'Poppins-Regular',
    fontSize: 13,
    color: '#555',
    marginBottom: 2,
  },
  ownerSince: {
    fontFamily: 'Poppins-Regular',
    fontSize: 12,
    color: '#999',
    marginTop: 2,
  },
  detailsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 16,
  },
  detailItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    width: '45%',
    paddingVertical: 6,
  },
  detailText: {
    fontFamily: 'Poppins-Regular',
    fontSize: 14,
    color: '#555',
  },
  amenities: {
    flexDirection: 'row',
    gap: 10,
    flexWrap: 'wrap',
  },
  amenityChip: {
    backgroundColor: '#f0fdf4',
  },
  amenityText: {
    fontSize: 12,
    fontFamily: 'Poppins-Medium',
    color: '#10b981',
  },
  description: {
    fontFamily: 'Poppins-Regular',
    fontSize: 14,
    color: '#555',
    lineHeight: 22,
  },
  addressRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginTop: 12,
    padding: 12,
    backgroundColor: '#fff',
    borderRadius: 10,
  },
  address: {
    fontFamily: 'Poppins-Regular',
    fontSize: 13,
    color: '#666',
    flex: 1,
  },
  messageBtn: {
    borderRadius: 12,
    height: 48,
    marginBottom: 8,
  },
  messageBtnText: {
    fontFamily: 'Poppins-SemiBold',
    fontSize: 14,
  },
  reviewsHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'baseline',
    marginBottom: 12,
  },
  averageRating: {
    fontFamily: 'Poppins-Bold',
    fontSize: 16,
    color: COLORS.primary,
  },
  review: {
    marginBottom: 16,
    padding: 16,
    backgroundColor: '#fff',
    borderRadius: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 1,
  },
  reviewHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  reviewAvatar: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#e9ecef',
  },
  reviewAvatarPlaceholder: {
    width: 40,
    height: 40,
    borderRadius: 20,
    justifyContent: 'center',
    alignItems: 'center',
  },
  reviewMeta: {
    flex: 1,
  },
  reviewAuthor: {
    fontFamily: 'Poppins-SemiBold',
    fontSize: 14,
    color: '#333',
    marginBottom: 4,
  },
  reviewDate: {
    fontSize: 11,
    fontFamily: 'Poppins-Regular',
    color: '#999',
  },
  reviewComment: {
    marginTop: 12,
    fontFamily: 'Poppins-Regular',
    fontSize: 13,
    color: '#555',
    lineHeight: 20,
  },
  addReviewSection: {
    marginTop: 16,
    padding: 16,
    backgroundColor: '#fff',
    borderRadius: 12,
  },
  ratingInput: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 16,
    marginBottom: 16,
  },
  ratingLabel: {
    fontFamily: 'Poppins-Medium',
    fontSize: 14,
    color: '#666',
  },
  reviewInput: {
    marginBottom: 16,
    backgroundColor: '#fff',
  },
  submitReviewBtn: {
    borderRadius: 12,
  },
  ownerActions: {
    flexDirection: 'row',
    gap: 10,
    marginBottom: 16,
  },
  ownerEditBtn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingVertical: 10,
    borderRadius: 10,
    borderWidth: 1.5,
    borderColor: COLORS.primary,
    backgroundColor: '#fff',
  },
  ownerEditText: {
    fontFamily: 'Poppins-SemiBold',
    fontSize: 13,
    color: COLORS.primary,
  },
  ownerDeleteBtn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingVertical: 10,
    borderRadius: 10,
    borderWidth: 1.5,
    borderColor: '#fecaca',
    backgroundColor: '#fff',
  },
  ownerDeleteText: {
    fontFamily: 'Poppins-SemiBold',
    fontSize: 13,
    color: '#ef4444',
  },
  modalContainer: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.95)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  closeModalBtn: {
    position: 'absolute',
    top: 40,
    right: 20,
    zIndex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    borderRadius: 25,
    padding: 8,
  },
  fullScreenImage: {
    width,
    height,
  },
  shareOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'flex-end',
  },
  shareSheet: {
    backgroundColor: '#fff',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    paddingHorizontal: 24,
    paddingBottom: 40,
    paddingTop: 12,
  },
  shareHandle: {
    width: 40,
    height: 4,
    borderRadius: 2,
    backgroundColor: '#ddd',
    alignSelf: 'center',
    marginBottom: 20,
  },
  shareTitle: {
    fontFamily: 'Poppins-SemiBold',
    fontSize: 16,
    color: '#333',
    textAlign: 'center',
    marginBottom: 24,
  },
  shareOptions: {
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 32,
    marginBottom: 28,
  },
  shareOption: {
    alignItems: 'center',
    gap: 8,
  },
  shareOptionIcon: {
    width: 60,
    height: 60,
    borderRadius: 30,
    justifyContent: 'center',
    alignItems: 'center',
  },
  shareOptionLabel: {
    fontFamily: 'Poppins-Medium',
    fontSize: 12,
    color: '#555',
  },
  shareCancelBtn: {
    paddingVertical: 14,
    borderRadius: 12,
    backgroundColor: '#f3f4f6',
    alignItems: 'center',
  },
  shareCancelText: {
    fontFamily: 'Poppins-SemiBold',
    fontSize: 14,
    color: '#555',
  },
});
